- hosts: all
  vars:
          - direc_nn: /root/task11
  tasks:
  - name: Copying the hadoop .rpm files into the Target node
    copy:
       src: /root/ansible/hadoop-1.2.1-1.x86_64.rpm
       dest: /root/
  - name: Importing the hadoop dependency java JDK
    copy:
       src: /root/ansible/jdk-8u171-linux-x64.rpm
       dest: /root/
  - name: Installing the JDK
    package:
         name: jdk-8u171-linux-x64.rpm
         disable_gpg_check: yes
    #   shell: rpm -ivh jdk-8u171-linux-x64.rpm --nobest
   
  - name: Installing Hadoop
    shell: rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force
    ignore_errors: yes
  - name: we are going to Share the HDFS-site.xml file by using the variables
    template:
       src: /root/ansible/name-hdfs.txt
       dest: /etc/hadoop/hdfs-site.xml
  - name: Sending Core-site.xml file to the respective directory.
    template:
            src: /root/ansible/name-core.txt
            dest: /etc/hadoop/core-site.xml
  - name: Create directory to share over hdfs network
    file:
            path: "{{direc_nn}}"
            state: directory
  - name: Format the name node to start it
    shell: echo Y | hadoop namenode -format
  - name: Starting the Master node
    shell: hadoop-daemon.sh start namenode
  - name: Status of about Master node start 
    debug: 
     msg: "Name Node just Started if it appears in Green or yellow"

